from io import BytesIO

from agents.smart_loader import SmartLoaderAgent


def make_uploaded_file(content: str, name: str) -> BytesIO:
    uploaded_file = BytesIO(content.encode("utf-8"))
    uploaded_file.name = name
    return uploaded_file


def test_smart_loader_loads_clean_csv():
    content = """product,region,revenue,quantity
Laptop,HCMC,1200,3
Mouse,Hanoi,150,10
"""

    uploaded_file = make_uploaded_file(content, "clean_sales.csv")

    loader = SmartLoaderAgent()
    loaded_dataset = loader.load(uploaded_file)

    df = loaded_dataset.dataframe
    metadata = loaded_dataset.metadata

    assert df.shape == (2, 4)
    assert list(df.columns) == ["product", "region", "revenue", "quantity"]
    assert metadata["detected_header_row"] == 0


def test_smart_loader_detects_messy_header_csv():
    content = """Sales Report Q1 2026,,,
Generated by system,,,
,,,
product,region,revenue,quantity
Laptop,HCMC,1200,3
Mouse,Hanoi,150,10
"""

    uploaded_file = make_uploaded_file(content, "messy_sales.csv")

    loader = SmartLoaderAgent()
    loaded_dataset = loader.load(uploaded_file)

    df = loaded_dataset.dataframe
    metadata = loaded_dataset.metadata

    assert df.shape == (2, 4)
    assert list(df.columns) == ["product", "region", "revenue", "quantity"]
    assert metadata["detected_header_row"] == 3


def test_smart_loader_removes_empty_rows_and_columns():
    content = """product,region,revenue,quantity,
Laptop,HCMC,1200,3,
,,,,
Mouse,Hanoi,150,10,
"""

    uploaded_file = make_uploaded_file(content, "empty_rows_columns.csv")

    loader = SmartLoaderAgent()
    loaded_dataset = loader.load(uploaded_file)

    df = loaded_dataset.dataframe

    assert df.shape == (2, 4)
    assert list(df.columns) == ["product", "region", "revenue", "quantity"]