from io import BytesIO

import pandas as pd

from core.pipeline import SpreadsheetPipeline


def make_uploaded_file(content: str, name: str) -> BytesIO:
    uploaded_file = BytesIO(content.encode("utf-8"))
    uploaded_file.name = name
    return uploaded_file


def test_pipeline_loads_messy_csv_and_profiles_dataset():
    content = """Sales Report Q1 2026,,,,
Generated by internal system,,,,
,,,,
product,region,revenue,discount_rate,order_date
Laptop,HCMC,"1,200",10%,2026-01-01
Mouse,Hanoi,150,15%,2026-01-02
Keyboard,HCMC,300,20%,2026-01-03
Monitor,Danang,,5%,2026-01-04
"""

    uploaded_file = make_uploaded_file(content, "week_2_mixed_types.csv")

    pipeline = SpreadsheetPipeline()
    result = pipeline.run(uploaded_file)

    df = result.dataframe
    metadata = result.metadata
    profile = result.profile
    normalization_report = result.normalization_report

    assert metadata["detected_header_row"] == 3
    assert df.shape == (4, 5)

    assert list(df.columns) == [
        "product",
        "region",
        "revenue",
        "discount_rate",
        "order_date",
    ]

    assert pd.api.types.is_numeric_dtype(df["revenue"])
    assert pd.api.types.is_numeric_dtype(df["discount_rate"])
    assert pd.api.types.is_datetime64_any_dtype(df["order_date"])

    assert profile["shape"]["rows"] == 4
    assert profile["shape"]["columns"] == 5
    assert profile["missing_values"]["revenue"] == 1

    conversions = normalization_report["conversions"]
    converted_columns = {
        conversion["column"]: conversion["conversion"]
        for conversion in conversions
    }

    assert converted_columns["discount_rate"] == "percentage_to_decimal"
    assert converted_columns["order_date"] == "date_string_to_datetime"


def test_pipeline_generates_numeric_and_categorical_summary():
    content = """product,region,revenue,quantity
Laptop,HCMC,1200,3
Mouse,Hanoi,150,10
Laptop,HCMC,1200,3
Keyboard,Danang,300,5
"""

    uploaded_file = make_uploaded_file(content, "summary_test.csv")

    pipeline = SpreadsheetPipeline()
    result = pipeline.run(uploaded_file)

    profile = result.profile

    assert "revenue" in profile["numeric_summary"]
    assert profile["numeric_summary"]["revenue"]["count"] == 4
    assert profile["numeric_summary"]["revenue"]["max"] == 1200

    assert "product" in profile["categorical_summary"]
    assert profile["categorical_summary"]["product"]["unique_count"] == 3
    assert profile["categorical_summary"]["product"]["top_values"]["Laptop"] == 2

    assert profile["duplicate_rows"] == 1