from __future__ import annotations

from dataclasses import dataclass

from llm.local_llm_client import LocalLLMClient, LLMResponse
from llm.prompt_templates import PromptTemplates


@dataclass
class LLMPlanningRefinementResult:
    success: bool
    refined_plan: str
    source: str
    model: str
    fallback_used: bool
    error: str | None
    warnings: list[str]


class LLMPlanningRefinementAgent:
    """
    Optional LLM-assisted planning refinement.

    This agent does not create the plan from scratch.
    It only refines a deterministic plan generated by PlanningAgent.
    """

    def __init__(self, llm_client: LocalLLMClient) -> None:
        self.llm_client = llm_client

    def refine_plan(
        self,
        user_question: str,
        deterministic_plan: str,
        language: str = "en",
    ) -> LLMPlanningRefinementResult:
        warnings: list[str] = []

        status = self.llm_client.get_status()

        if not status.available:
            return self._fallback(
                deterministic_plan=deterministic_plan,
                error=status.message,
                warnings=[status.message],
            )

        model_validation = self.llm_client.validate_model()

        if not model_validation.is_valid:
            warnings.append(model_validation.message)

            return self._fallback(
                deterministic_plan=deterministic_plan,
                error=model_validation.message,
                warnings=warnings,
            )

        prompt = PromptTemplates.planning_refinement_prompt(
            user_question=user_question,
            deterministic_plan=deterministic_plan,
            language=language,
        )

        response: LLMResponse = self.llm_client.generate(
            prompt=prompt,
            system_prompt=(
                "You refine deterministic spreadsheet analysis plans. "
                "Do not invent columns. Do not add unsupported steps. "
                "Keep the original workflow intent."
            ),
            temperature=0.2,
            max_tokens=500,
        )

        if not response.success:
            return self._fallback(
                deterministic_plan=deterministic_plan,
                error=response.error,
                warnings=[response.error or "Unknown LLM planning refinement error."],
            )

        refined_plan = response.content.strip()

        if not refined_plan:
            warnings.append("LLM returned an empty planning refinement.")

            return self._fallback(
                deterministic_plan=deterministic_plan,
                error="Empty LLM planning refinement.",
                warnings=warnings,
            )

        return LLMPlanningRefinementResult(
            success=True,
            refined_plan=refined_plan,
            source="local_llm",
            model=self.llm_client.model_name,
            fallback_used=False,
            error=None,
            warnings=warnings,
        )

    def _fallback(
        self,
        deterministic_plan: str,
        error: str | None,
        warnings: list[str],
    ) -> LLMPlanningRefinementResult:
        return LLMPlanningRefinementResult(
            success=False,
            refined_plan=deterministic_plan,
            source="deterministic_fallback",
            model=self.llm_client.model_name,
            fallback_used=True,
            error=error,
            warnings=warnings,
        )